### ISSUE TITLE
Search user (Frontend)

### ISSUE THREAD

**Issue by FredrikEH** [boolean-uk/team-dev-client-ex-2410-team3#23]
Requirements:

A user should be able to search for any other users, teachers and students. A search is made with either first name or last name or both first and last name. Names should not be case sensitive. When the user submits the search query, the user will be taken to a page showing a list of all matching users. If there is no user with the provided name, a message stating that there are no such users will be displayed.

Design: [Search](https://www.figma.com/design/j9QIHvgM0wOVw3xDe9KdWB/My-Copy%3A-Cohort-Manager-app---Designs?node-id=135-15021&node-type=frame) [Result](https://www.figma.com/design/j9QIHvgM0wOVw3xDe9KdWB/My-Copy%3A-Cohort-Manager-app---Designs?node-id=1732-16353&node-type=frame)

Plan

- Link search submit action to result page without a button
```
// pages/dashboard/index.js
<Card>
   // Change line below to link to search result page on submit
   <form onSubmit={(e) => e.preventDefault()}>
       // Change line below to submit on pressing enter key
      <TextInput icon={<SearchIcon />} value={searchVal} name="Search" onChange={onChange}/>
   </form>
</Card>
```

- Link search submit button to result page (Combine this with your Card if you want)
```js
// dashboard/index.js
import { useNavigate } from 'react-router-dom'
const Dashboard = () => {
    const navigate = useNavigate()
    const onSearch = (e) => {
        e.preventDefault()
        navigate(`dashboard/search/${searchTerm}`)
    }

    <form onSubmit={onSearch}>
}

// dashboard/search/index.js
import { useParams, useNavigate } from 'react-router-dom'
const Search = () => {
    const { searchTerm} = useParams();
    const [search, setSearch] = useState(searchTerm || '')
    const navigate = useNavigate()

    useEffect(() => {
        setSearch(searchTerm)
    }, [searchTerm])

    const handleChange = (e) => {
        setSearch(e.target.value)
    }

    const handleSubmit = (e) => {
        e.preventDefault()
        navigate(`/dashboard/search/${search}`)
    }

    return (
        <form onSubmit={handleSearchSubmit}>
            <TextInput ...props onChange={handleChange} />
        </form>
    )
}
```
- Create message on result page for when there are no matching results

**Comment by amos1969** [comment]
Approved
