### ISSUE TITLE
Display posts for student (frontend)

### ISSUE THREAD

**Issue by amos1969** [boolean-uk/team-dev-client-ex-2410-team3#24]
EPIC: Dashboard - Student View

Requirements:
A logged in user should be able to view all posts made by other users on their dashboard. Posts should be stacked in one column starting with the most recent being on top. Each post should display the user who posted it, when it was posted, its content, comments on the post, and have a like and toggle comments button. A post should display if it has been edited.

The design should adhere to the specs presented in Figma:
https://www.figma.com/design/j9QIHvgM0wOVw3xDe9KdWB/My-Copy%3A-Cohort-Manager-app---Designs?node-id=135-15021&node-type=frame

Plan:
1. Create listItem and the list to contain each item.
*Example of listItem*
```javascript
export default function PostItem({
    postItem: { SomeInfoOrSomething }
}) {
    return (
        <li>
			//something which displays the users information and post
      </li>
    );
}
```

*Example of list*
```javascript
  return (
    <ul>
      {contacts.map((postItem, i) => (
        <PostItem postItem={postItem} key={i} />
      ))}
    </ul>
  );
```

**Comment by amos1969** [comment]
Are there any Designs in Figma that should be linked in here?

**Comment by MalteStengard** [comment]
I have added a link to the figma design that should be utilized

**Comment by amos1969** [comment]
Approved
