### ISSUE TITLE
User Registration needs to validate password (Frontend)

### ISSUE THREAD

**Issue by FredrikEH** [boolean-uk/team-dev-client-ex-2410-team3#28]
EPIC: https://github.com/boolean-uk/team-dev-client-ex-2410-team3/issues/9

When a user creates a new account, they fill in an email and password. The app should validate the below conditions before letting the account be created, displaying a user friendly message if any check fails:

- The password should not be less than 8 characters in length
- [x] Add minlength to the password input field
```
minlength="8"
```

- The password should contain at least one uppercase character
- The password should contain at least one number
- The password should contain at least one special character
- [x] Add attribute `pattern` with regex to the password input field

Possible resource for client side validation here: https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation

- User friendly validation
- [x] Check if the built-in validation functionality provides enough user friendly messages
- [ ] Add the missing text about password requirements under the input field for the password.
- [x] Add the missing `* Required`  text under the input fields.

See design document: [Design](https://www.figma.com/design/j9QIHvgM0wOVw3xDe9KdWB/My-Copy%3A-Cohort-Manager-app---Designs?node-id=228-41540&t=ep6tuwERh4cTL9t4-0)

**Comment by amos1969** [comment]
Approved

**Comment by shyye** [comment]
The check point:

- "Add the missing text about password requirements under the input field for the password."

isn't implemented because `compnents/form/textInput/index.js` already displays those messages according to the validation in that component.
