### ISSUE TITLE
My Cohort Component

### ISSUE THREAD

**Issue by FredrikEH** [boolean-uk/team-dev-client-ex-2410-team3#30]
Create a "My Cohort" Component

### Cohort title
- [ ] Get current Cohort of the current user.

### Classmates
- [ ] Get all Classmates from the Cohort 
* - [ ]  Use Card for each Classmate in the cohort 

### Card component
Use the right amount of data into each classmate card as seen below:

```JS
 <Card>
            <section className="post-details">
              <div className="profile-icon">
                <p>AJ</p>
              </div>

              <div className="post-user-name">
                <p>Alex Jameson</p>
                <small>Software Developer, Cohort 3</small>
              </div>
            </section>
          </Card>
``` 

### Get Data

```
Get Data from API of the cohort by UserId
Set Cohort title using Card component

Get all Students from the Cohort with CohortID
Generate Card component for each Classmates
Use Card component and put the classmate Name into the card. 

```

Use this function to get the cohort. The endpoint variable is going to be "cohort/:id" depending on the users cohorts 

```JS
async function get(endpoint, auth = true) {
  return await request('GET', endpoint, null, auth);
}
```
This function will return the Cohort and all the data needed to get all classmates of the cohort

If the there are no Cohort in the database, use Mockup data for now until the backend is done.

[Design](https://www.figma.com/design/j9QIHvgM0wOVw3xDe9KdWB/My-Copy%3A-Cohort-Manager-app---Designs?node-id=238-11487&t=iDFZNDVtVyxnzyTz-1)

**Comment by amos1969** [comment]
Approved
