### ISSUE TITLE
Update Prisma to represent the API spec

### ISSUE THREAD

**Issue by FredrikEH** [boolean-uk/team-dev-client-ex-2410-team3#32]
The Prisma schema does not accurately portray the current API spec. Changes will be needed to made to both in order for them to do what they need to and to be accurate with each other.

Changes that will be done will for example be to update the prisma schema for post to go from:
```
model Post {
  id      Int           @id @default(autoincrement())
  content String
  userId  Int
  user    User          @relation(fields: [userId], references: [id])
}
```
to this:
```
model Post {
  id      Int           @id @default(autoincrement())
  content String
  createdAt String // New
  updatedAt String // New
  userId  Int
  user    User          @relation(fields: [userId], references: [id])
}
```

**Comment by sebgro98** [comment]
Approved

**Comment by Badde00** [comment]
> Are these the extent of all of the changes needed or just a sample?

It was a sample. I would also like to change other things, like
```
model User {
  // Other stuff
  profile       Profile?
  // Other stuff
}
```
to
```
model User {
  // Other stuff
  profile       Profile?    @relation(fields: [profileId], references: [id])
  // Other stuff
}
```
to make those fit together, which is needed to send the bio of a user.
Cohort also needs the createdAt/updateAt fields.
Those were the only ones I could find right now.

**Comment by amos1969** [comment]
Approved for the ones documented, if you want to change other things then they should be the subject of their own tickets
