### ISSUE TITLE
Bug: Fix the navigation (Frontend)

### ISSUE THREAD

**Issue by FredrikEH** [boolean-uk/team-dev-client-ex-2410-team3#36]
As of now. Once the user has signed in to Cohort Manager, the user cannot move away from path /. 
This bug is due to this useEffect in context/auth.js

```JS
  const navigate = useNavigate();
  const location = useLocation();

... 

  useEffect(() => {
    const storedToken = localStorage.getItem('token');

    if (storedToken) {
      setToken(storedToken);
      navigate(location.state?.from?.pathname || '/');
    }
  }, [location.state?.from?.pathname, navigate]);

```
The useEffect in AuthProvider is causing an unintended redirect loop. This is because location.state.from.pathname is being used in the useEffect dependency array. Whenever location.state.from.pathname changes, useEffect is triggered again, potentially causing repeated navigation attempts.

The downside of using location.state.from.pathname is that when you want to redirect the user you need to se this in the redirection tag:
```JS
// This is needed to change the state
const location = useLocation();
...

 <li>
          <NavLink to="/cohort">
            <CohortIcon />
            <p>Cohort</p>
          </NavLink>
        </li>
```

It is linked to this Issue from the team-dev-client-template:
https://github.com/boolean-uk/team-dev-client-template/issues/80

Solution:
Using useLocation, you can set so the user can write the path themself in the browser. For instance:
![Image](https://github.com/user-attachments/assets/2f40ac9c-b278-4eea-9578-95b9b3092051)

and the user will be taken to the welcome page. The solution is to remove location.state?.from?.pathname to just location.pathname as seen in this documentation:
https://reactrouter.com/en/main/hooks/use-location

**Comment by amos1969** [comment]
Approved
