### ISSUE TITLE
Implement User Profile Edit Page (Frontend)

### ISSUE THREAD

**Issue by SimpFred** [boolean-uk/team-dev-client-ex-2410-team3#44]

**Comment by SimpFred** [comment]
- **EPIC**: Registration & Create User Profile [#9](https://github.com/boolean-uk/team-dev-client-ex-2410-team3/issues/9)

- **Description**: Enable edit functionality by using the existing `ProfilePage.jsx` component, adjusting field edit permissions based on the user's role.

- **Acceptance Criteria**:
  - If the user is a student, fields for training information should be disabled.
  - Teachers should have the ability to edit all fields, including role and cohort.
  - Only the profile owner should be able to modify the password field.

- **Plan**:

  1. **Modify Existing Route for Editable Profile**:
     - Ensure the `/profile/:id/edit` route renders `ProfilePage.jsx` with an edit mode.
     ![Image](https://github.com/user-attachments/assets/6b2a963e-a0ea-4ced-b83a-7f2868aca70e)

  2. **Enable Editable Fields in ProfilePage Component**:
     - Add logic to `ProfilePage.jsx` to check if the component is in edit mode (e.g., based on route or a passed prop).
     - Set conditional rendering for fields, such as:
       - Allow all fields to be editable for teachers.
       - Allow students to edit basic info but disable fields regarding training info.
       - Make the password field editable only for the profile owner.

  3. **Add Validation Rules for Editable Fields**:
     - Apply validation to input fields, particularly for the password field (e.g., minimum length requirements).
     - Show error messages or validation indicators where appropriate.

  4. **Implement Save Button and Functionality**:
     - Add a "Save" button to submit updates to the profile.
     - Connect the button to form submission logic, ensuring API integration to save changes (if implemented, else print out the edited profile).
     - Provide feedback to the user upon successful update or error.

  5. **Test and Verify**:
     - Test edit permissions based on user roles to ensure correct functionality.
     - Verify conditional rendering of fields, and that fields are only editable when appropriate.
     - Test the API integration to confirm updates are correctly saved and displayed. (If implemented)

**Comment by amos1969** [comment]
How are you handling changing the Password?

**Comment by SimpFred** [comment]
Translation: I am checking if the currently logged-in user has the same ID as the profile being displayed at the moment by using these:
`const { profileId } = useParams();
const { token } = useAuth();
const { userId } = jwt_decode(token);`

**Comment by SimpFred** [comment]
Or do you mean how I then handle the password?

**Comment by amos1969** [comment]
What is the process? 

- Typically if you want to change the password on a site, you re-enter the current password and then enter the new password twice. Is that what will happen?

- If a site is able to display the current password to you, then that implies that it is stored insecurely (ie not encrypted), which is a really bad idea.

**Comment by SimpFred** [comment]
Okay, that might be a separate ticket then. I can add a note in this issue that it will not be implemented yet, is that ok?

**Comment by amos1969** [comment]
Sure, so specifically exclude being able to change the Password from this part then.

**Comment by SimpFred** [comment]
Done
