### ISSUE TITLE
Store User Role Along with Token

### ISSUE THREAD

**Issue by SimpFred** [boolean-uk/team-dev-client-ex-2410-team3#46]
# EPIC: Registration & Create User Profile [#9](https://github.com/boolean-uk/team-dev-client-ex-2410-team3/issues/9)

- **Description**: Currently, the application only stores the authentication token in local storage and state. To improve functionality, we need to store the user's role as well, enabling more effective user permissions and access control.

- **Tasks**:

  1. **Add State for Role**:
     - Add a new state variable `role` to store the user's role.

  2. **Update `useEffect` Hook**:
     - Retrieve the stored role from local storage along with the token.
     - Set the `role` state if it exists in local storage.

  3. **Update `handleLogin` Function**:
     - Store the user's role in local storage upon successful login.
     - Set the `role` state with the retrieved role.

  4. **Update `handleLogout` Function**:
     - Remove the role from local storage upon logout.
     - Reset the `role` state to `null`.

  5. **Update `handleRegister` Function**:
     - Store the user's role in local storage upon successful registration.
     - Set the `role` state with the retrieved role.

  6. **Update `AuthContext` Provider**:
     - Include the `role` state in the context value for access throughout the application.

- **Acceptance Criteria**:
  - The user's role is stored in local storage along with the token.
  - The `role` state is correctly set and retrieved from local storage.
  - The `role` is included in the `AuthContext` and accessible throughout the application.
  - The role is removed from local storage and state upon logout.

**Comment by amos1969** [comment]
Approved

**Comment by SimpFred** [comment]
Can I change this issue to store the user object instead of just the role? I noticed that the user is return with the token
