### ISSUE TITLE
Updating User Profile Data - (Frontend)

### ISSUE THREAD

**Issue by Yumikitsu** [boolean-uk/team-dev-client-ex-2410-team3#47]
### Requirements:

When creating a user at the register stage, the User needs to have the following fields defined in the database model:
```prisma
model User {
  id            Int       @id @default(autoincrement())
  email         String    @unique
  password      String
  role          Role      @default(STUDENT)
  specialism   String
  profile       Profile?
  cohortId      Int?
  cohorts       Cohort[]
  posts         Post[]
  comments      Comment[]
  deliveryLogs  DeliveryLog[]
}
```
The email and password are already given to it upon registration and the specialism should be set to "Software Developer", and the role should be set to "Student", but the Profile also needs to be created upon registration and assigned to the User. The Profile needs to have the following fields defined:
```prisma
model Profile {
  id          Int       @id @default(autoincrement())
  userId      Int       @unique
  user        User      @relation(fields: [userId], references: [id])
  firstName   String
  lastName    String
  username String
  githubUsername   String
  bio         String
  profilePicture   String
  mobile   String
}
```
Now that the User and Profile is defined, we can perform frontend API calls in the Welcome Page to first get the data with an initial fetch and then updates the empty data to valid data when submitting the Welcome Page form using PATCH/PUT API calls for Profile as all the User data cannot be altered in the form at this stage.

The Welcome Page will have the following data, where cohort, startDate and endDate are dummy values until a solution is figured out.

```js
firstName: '',
lastName: '',
username: '',
githubUsername: '',
bio: '',
profilePicture: '',
email: '',
mobile: '',
password: '',
role: '',
specialism: '',
cohort: '',
startDate: '',
endDate: ''
```

Both the Welcome Page and User Edit are depending on similar API calls.

[Welcome Page](https://www.figma.com/design/j9QIHvgM0wOVw3xDe9KdWB/My-Copy%3A-Cohort-Manager-app---Designs?node-id=204-8131&t=zEFtsoD0sKc7tig8-0)

[User Edit](https://www.figma.com/design/j9QIHvgM0wOVw3xDe9KdWB/My-Copy%3A-Cohort-Manager-app---Designs?node-id=195-8008)

### Plan
- Need to wait for backend to fully test and implement.

Frontend:
- Update the API calls to fetch and send the necessary information to the database
```js
// context/auth.js
async function updateProfile(
  userId,
  firstName,
  lastName,
  username,
  githubUsername,
  bio,
  profilePicture,
  mobile
) {
  return await patch(`profiles/${userId}`, {
  userId,
  firstName,
  lastName,
  username,
  githubUsername,
  bio,
  profilePicture,
  mobile
  });
}

// pages/welcome/index.js
  const onComplete = () => {
    if (validate(0)) {
      onCreateProfile(
        profile.firstName,
        profile.lastName,
        profile.username,
        profile.githubUsername,
        profile.bio,
        profile.profilePicture,
        profile.mobile
      );
    }
  };
```

- Get the data when the page first navigates to welcome by using useEffect and doing a GET request:

```js
// welcome/index.js
- Add function to add user data to profile -
- Add function to add profile data to profile -
useEffect(() => {
  get(UserEndpoint).then(setUserData);
  get(ProfileEndpoint).then(setProfileData);
}, []);
```

**Comment by amos1969** [comment]
Approved
