### ISSUE TITLE
Make a drop down menu for "My Cohort" (Frontend)

### ISSUE THREAD

**Issue by FredrikEH** [boolean-uk/team-dev-client-ex-2410-team3#60]
Make a drop down menu for "My Cohort" page where the logged in user can change the view of current cohort. So for instance, if the student is in 3 cohorts, the student will be able to switch the view of the current cohort as seen in this picture.

![Image](https://github.com/user-attachments/assets/dd550958-fae6-44c7-926f-1b6945b11c98)

**Comment by amos1969** [comment]
Approved

Impressive graphic design skills on display
