### ISSUE TITLE
Fetch and store profile data from database in user profile page (Frontend)

### ISSUE THREAD

**Issue by SimpFred** [boolean-uk/team-dev-client-ex-2410-team3#61]
# EPIC:  Registration & Create User Profile [#9](https://github.com/boolean-uk/team-dev-client-ex-2410-team3/issues/9)

- **Description**: Transition from using mock data to retrieving and storing actual user profile data from the database via the `profiles` endpoint. This will enable the profile page to display real user data and persist any changes.

- **Tasks**:

  1. **Set Up API Call to Fetch Profile Data**:
     - Replace mock data with an API call to `profiles/${profileId}`.
     - Implement error handling to manage cases when data retrieval fails.

  2. **Populate ProfilePage Component with Fetched Data**:
     - Update the state in `ProfilePage.jsx` to store data fetched from the API.
     - Ensure all fields are populated dynamically with the retrieved data.

  3. **Implement Save Functionality to Update Profile**:
     - Create a function that sends updated profile data to the `profiles/${profileId}` endpoint.

  4. **Test Full Data Retrieval and Save Cycle**:
     - Test that profile data loads correctly upon page visit.
     - Verify that updated profile information persists in the database after editing and saving.

- **Acceptance Criteria**:
  - The profile page retrieves data from the `profiles/${profileId}` endpoint and displays it accurately.
  - Any changes made to the profile are saved to the database and reflect on subsequent page loads.
  - Error handling is implemented for both data retrieval and save actions.

**Comment by amos1969** [comment]
Approved
