### ISSUE TITLE
Fill up "My Cohort" list on the dashboard (Frontend)

### ISSUE THREAD

**Issue by sebgro98** [boolean-uk/team-dev-client-ex-2410-team3#65]
Update the Dashboard so the user can see "My Cohort" on the dashboard. The data should be a list and if the user clicks on it, the user should be redirected to the correct cohort. As seen on the picture

![Image](https://github.com/user-attachments/assets/73e94233-8dcb-4a72-a6b8-58eae46bba10)

**Comment by amos1969** [comment]
Approved
