### ISSUE TITLE
Add a Student view of cohort and a teachers view of cohort

### ISSUE THREAD

**Issue by sebgro98** [boolean-uk/team-dev-client-ex-2410-team3#69]
As of now, every user can view the cohort and see all the buttons. In the Epic, the teacher is the only user role to be able to see the buttons. Also for future implementation, create a "Add Cohort" button on "My Cohort" page using Modal.

To  do this, generate a new file, teachersView and a studentView page. In /cohort/index,js, check what role the user has, if the user is a teacher show teachersView, otherwise show studentView page.

**Comment by amos1969** [comment]
Approved
